### ISSUE TITLE
some blocks are not rendered normally with some resource packs. (CTM)

### ISSUE THREAD

**Issue by Lolothepro** [mateusak/minecraft-miniature-shader#2]
https://user-images.githubusercontent.com/68275908/218324142-e6fa564a-e659-452b-b52b-f92b0e151e6b.mp4

**Comment by mateusak** [comment]
Not enough information.

**Comment by Lolothepro** [comment]
> Not enough information.

What additional information do you need?

**Comment by Lolothepro** [comment]
> the shader pack is likely not properly handling vertex color & cutout effects for dirt blocks.

Coderbot

**Comment by mateusak** [comment]
> > Not enough information.
> 
> What additional information do you need?

Minecraft version, resource pack used, etc, but the reason I closed is because it seems to be ~1.12 faithful, in which case I won't solve it. I couldn't reproduce in newer versions.

**Comment by Lolothepro** [comment]
[Sama Faithful 2.1.1 (1.19.3)](https://mega.nz/folder/jBljBLib#E4H5KkHgcO0e5dHfSNYsDw)

**Comment by mateusak** [comment]
> [Sama Faithful 2.1.1 (1.19.3)](https://mega.nz/folder/jBljBLib#E4H5KkHgcO0e5dHfSNYsDw)

It's the resource pack's fault, as it sets the grass blocks overlays on the translucent layer, instead of cutout. 

Also it was easy to see in-game that the blocks become reflective, but your video doesn't make that clear at all because of your angle. Provide more information when you open issues, especially when it's something done for free.
